### PR TITLE
Fix utf8 encoding problem

### PR DESCRIPTION
**Pull request by at15**
see #15 , when deal with utf8 encoding strings, it will get wrong output. add `u` solve it. thanks to @eos-13 this pr should fix it.

### CODE REVIEW

**Comment by at15** [comment]
e ... travis build for php5.5 fails, but 5.4 and 5.6 pass, strange ...

**Comment by gajus** [comment]
@at15 Have you figured out why Travis build for 5.5 is failing?

**Comment by at15** [comment]
@gajus from travis log 

> This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.

so travis run PHPUnit5.0+ on PHP 5.5 environment and thus failed, but I don't know why the previous builds pass on PHP 5.5, maybe because travis was still using PHPUnit4.x for PHP 5.5 at that time. 

And if we use `requrie-dev` and specify the phpunit version instead of using the global one, it should pass.

**Comment by KennedyTedesco** [comment]
:+1:

**Comment by Schleuse** [comment]
Works like a charm 🦄

**Pull request merged**
